### ISSUE TITLE
Trying to use this recipe for custom polars.

### ISSUE THREAD

**Issue by chebee7i** [conda-forge/polars-feedstock#178]
### Comment:

Hi, I'm trying to use this receipe to build a custom polars version that includes `bigidx` support.  Largely, I am copying the `recipe` directory, but I'm finding that it doesn't work as is. This is from a `conda debug` preparation:
```console
$ bash conda_build.sh
+ [[ linux-64 == \l\i\n\u\x\-\6\4 ]]
+ export 'RUSTFLAGS=-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma'
+ RUSTFLAGS='-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma'
+ echo rustc --version
rustc --version
+ /home/username/conda-bld/debug_1696198149242/_h_env/bin/python -m pip install . -vv
Using pip 23.2.1 from /home/username/conda-bld/debug_1696198149242/_h_env/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-build-tracker-btais1hi
Initialized build tracking at /tmp/pip-build-tracker-btais1hi
Created build tracker: /tmp/pip-build-tracker-btais1hi
Entered build tracker: /tmp/pip-build-tracker-btais1hi
Created temporary directory: /tmp/pip-install-zjqnqt8k
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Exception information:
Traceback (most recent call last):
  File "/home/username/conda-bld/debug_1696198149242/_h_env/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/username/conda-bld/debug_1696198149242/_h_env/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/username/conda-bld/debug_1696198149242/_h_env/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 342, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/home/username/conda-bld/debug_1696198149242/_h_env/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 414, in get_requirements
    req_to_add = install_req_from_line(
  File "/home/username/conda-bld/debug_1696198149242/_h_env/lib/python3.8/site-packages/pip/_internal/req/constructors.py", line 395, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
  File "/home/username/conda-bld/debug_1696198149242/_h_env/lib/python3.8/site-packages/pip/_internal/req/constructors.py", line 310, in parse_req_from_line
    url = _get_url_from_path(p, name)
  File "/home/username/conda-bld/debug_1696198149242/_h_env/lib/python3.8/site-packages/pip/_internal/req/constructors.py", line 266, in _get_url_from_path
    raise InstallationError(
pip._internal.exceptions.InstallationError: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Removed build tracker: '/tmp/pip-build-tracker-btais1hi'
```
The issue is that it is trying to do the pip install outside of the source directory. So I had to modify `build.sh` to include a `cd py-polars`:
```console
# Run the maturin build via pip which works for direct and
# cross-compiled builds.
cd py-polars                        # This line is new!
$PYTHON -m pip install . -vv
```
How is this working normally as part of the feedstock? Is this just a quick of how feedstock is set up?

----

Even with the updated `build.sh`, I still get failures:
```console
$ bash conda_build.sh
+ [[ linux-64 == \l\i\n\u\x\-\6\4 ]]
+ export 'RUSTFLAGS=-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma'
+ RUSTFLAGS='-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma'
+ echo rustc --version
rustc --version
+ cd py-polars
+ OPENSSL_CONF=conf/openssl.conf
+ /home/username/conda-bld/debug_1696198149242/_h_env/bin/python -m pip install . -vv
Using pip 23.2.1 from /home/username/conda-bld/debug_1696198149242/_h_env/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-build-tracker-pbpp8ns1
Initialized build tracking at /tmp/pip-build-tracker-pbpp8ns1
Created build tracker: /tmp/pip-build-tracker-pbpp8ns1
Entered build tracker: /tmp/pip-build-tracker-pbpp8ns1
Created temporary directory: /tmp/pip-install-do79rq7q
Created temporary directory: /tmp/pip-ephem-wheel-cache-2_fw60tk
Processing /home/username/conda-bld/debug_1696198149242/work/py-polars
  Added file:///home/username/conda-bld/debug_1696198149242/work/py-polars to build tracker '/tmp/pip-build-tracker-pbpp8ns1'
  Created temporary directory: /tmp/pip-modern-metadata-1rk7tgbo
  Running command Preparing metadata (pyproject.toml)
      Updating crates.io index
      Updating git repository `https://github.com/jorgecarleitao/arrow2`
      Updating git submodule `https://github.com/apache/arrow-testing`
      Updating git submodule `https://github.com/apache/parquet-testing`
      Updating git repository `https://github.com/ritchie46/jsonpath`
  error: failed to select a version for `arrow2`.
      ... required by package `polars-core v0.32.0 (/home/username/conda-bld/debug_1696198149242/work/crates/polars-core)`
      ... which satisfies path dependency `polars-core` (locked to 0.32.0) of package `polars v0.32.0 (/home/username/conda-bld/debug_169619814924
2/work/crates/polars)`
      ... which satisfies path dependency `polars` (locked to 0.32.0) of package `py-polars v0.19.3 (/home/username/conda-bld/debug_1696198149242/
work/py-polars)`
  versions that meet the requirements `*` (locked to 0.17.4) are: 0.17.4

  the package `polars-core` depends on `arrow2`, with features: `bigidx` but `arrow2` does not have these features.


  failed to select a version for arrow2` which could resolve this conflict
  💥 maturin failed
   Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
    Caused by: `cargo metadata` exited with an error:
  Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-1rk7tgbo', '--interpreter', '/home/username/conda-bld/debug_1696198149242/_h_env/bin/pyt
hon']' returned non-zero exit status 1.
  Checking for Rust toolchain....
  Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-1rk7tgbo --interpreter /home/username/conda-bld/debug_1696198149242/_h_env/bin/python`
  error: subprocess-exited-with-error
```

Any suggestions?

**Comment by 0xbe7a** [comment]
After #179 is fixed, you can use `maturin sdist` inside `py-polars` to create a source distribution `polars-....tar.gz` with the same folder structure and should be able to use the recipe as is.
